apiVersion: metallb.io/v1beta1
kind:  IPAddressPool
metadata:
  name: lb-address-pool
  namespace: metallb
spec:
  addresses:
    - 142.3.6.100-142.3.6.105
  autoAssign: true

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lb-advertisement
  namespace: metallb
spec:
  ipAddressPools:
    - lb-address-pool
